### ISSUE TITLE
TJV: Move Morph.io API key to the secret values

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/imamopravoznati-utilities#7]
**Where to implement the change:**
"Morph script" - script that parses TJV register and persists it to db
https://morph.io/SelectSoft/blue_gene

**Current:**
API key is stored in the public python code:
https://github.com/SelectSoft/blue_gene/blob/master/scraper.py#L129 (see `key=`)

**Expected:**
Move key to a Morph.io secret values.
See documentation: https://morph.io/documentation/secret_values

### Move Morph.io API key to the secret values

See Morp.io documentation.

**Comment by SelectSoft** [comment]
Done

**Comment by schlos** [comment]
This is implemented via https://github.com/SelectSoft/blue_gene/blob/master/scraper.py#L145 and https://github.com/SelectSoft/blue_gene/blob/master/scraper.py#L146, closing.
